# Generated by Django 5.1.7 on 2025-03-27 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=225,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
