# Generated by Django 5.1.7 on 2025-03-27 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=225)),
                ("description", models.TextField()),
                ("tags", models.CharField(max_length=225)),
                ("ai_relevance_score", models.FloatField()),
                ("likes", models.IntegerField(default=0)),
                ("viewed", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="authentication.category",
                    ),
                ),
            ],
        ),
    ]
