# Generated by Django 5.1.7 on 2025-03-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_subscriptionplan_remove_content_likes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="is_active",
        ),
    ]
