# Generated by Django 5.1.7 on 2025-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_subscriptionplan_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
