# Generated by Django 5.1.7 on 2025-03-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_usersubscription_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="is_active",
        ),
    ]
