# Generated by Django 5.1.7 on 2025-03-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remove_usersubscription_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="created_at",
            new_name="liked_at",
        ),
        migrations.RenameField(
            model_name="views",
            old_name="created_at",
            new_name="viewed_at",
        ),
    ]
