# Generated by Django 5.1.7 on 2025-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_rename_created_at_like_liked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="liked_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="views",
            name="viewed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
