# Generated by Django 5.1.7 on 2025-03-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_like_liked_at_alter_views_viewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="content",
            name="unlikes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="content",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
